[package]
name = "example-forms-utils"
version = "0.1.0"
authors = ["sync-team@mozilla.com"]
license = "MPL-2.0"
edition = "2018"
publish = false

[[example]]
name = "forms-utils"
path = "src/forms-utils.rs"

[dev-dependencies]
anyhow = "1.0"
cli-support = { path = "../cli-support" }
structopt = "0.3"
